# Generated by Django 5.2.5 on 2025-09-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other')], default='Undergraduate', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='nationality',
            field=models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
