# Generated by Django 5.2.5 on 2025-08-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='research_type',
            field=models.CharField(choices=[('Environment & Marine', 'Environment & Marine'), ('Aquatic Organisms', 'Aquatic Organisms'), ('Fisheries Research', 'Fisheries Research')], default='Environment & Marine', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='control_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
