# Generated by Django 5.2.5 on 2025-08-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_payment_research_type_alter_payment_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='research_type',
            field=models.CharField(blank=True, choices=[('Environment & Marine', 'Environment & Marine'), ('Aquatic Organisms', 'Aquatic Organisms'), ('Fisheries Research', 'Fisheries Research')], max_length=100, null=True),
        ),
    ]
