# Generated by Django 5.2.5 on 2025-09-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_payment_currency_remove_payment_level_and_more'),
    ]

    operations = [
    ]
