# Generated by Django 5.2.5 on 2025-09-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_add_important_field'),
    ]

    operations = [
    ]
