# Generated by Django 5.2.5 on 2025-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_research_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='important',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
