# Generated by Django 5.2.5 on 2025-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_important_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='research_type',
            field=models.CharField(blank=True, choices=[('Environment & Marine', 'Environment & Marine'), ('Aquatic Organisms', 'Aquatic Organisms'), ('Fisheries Research', 'Fisheries Research')], max_length=100, null=True),
        ),
    ]
