# Generated by Django 5.2.5 on 2025-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Officer', 'Officer'), ('Researcher', 'Researcher')], max_length=20, null=True),
        ),
    ]
