# Generated by Django 5.2.5 on 2025-09-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_bio_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='officer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
