# Generated by Django 5.2.5 on 2025-09-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_certificate_officer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Master', 'Master'), ('PhD', 'PhD'), ('Other', 'Other')], default='Undergraduate', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='nationality',
            field=models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local', max_length=10),
        ),
    ]
