# Generated by Django 5.2.5 on 2025-09-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_payment_level_payment_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='nationality',
        ),
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
