# Generated by Django 5.2.5 on 2025-09-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_payment_level_remove_payment_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
        migrations.AddField(
            model_name='payment',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Foreign', 'Foreign')], max_length=50, null=True),
        ),
    ]
