# Generated by Django 5.2.5 on 2025-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_payment_category_payment_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
