# Generated by Django 5.2.5 on 2025-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_payment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='offline_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/offline/'),
        ),
    ]
