# Generated by Django 5.2.5 on 2025-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_certificate_offline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
    ]
