# Generated by Django 5.2.5 on 2025-09-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='level',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PhD', 'PhD'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nationality',
            field=models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local', max_length=50),
        ),
    ]
