# Generated by Django 5.2.5 on 2025-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_payment_level_alter_payment_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
