# Generated by Django 5.2.5 on 2025-09-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Foreign', 'Foreign')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Expired', 'Expired')], max_length=20),
        ),
    ]
