# Generated by Django 5.2.5 on 2025-09-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_payment_amount_alter_payment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('Vice President Form', 'Vice President Form'), ('Proposal', 'Proposal'), ('Ethical Form', 'Ethical Form')], max_length=50),
        ),
    ]
